# Replace the text below to customize your site
site_name: Jorge De la Mora | MDEF & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: Jorge DLM
copyright: Copyleft 2023 "Jorge De la Mora"
repo_name: 'JDLM : Github'
site_url: https://jdlm92.github.io/MDEFsite/
repo_url: 'https://github.com/JDLM92/MDEFsite'


nav:
  - Home: index.md
  - About: about/me.md
  - Master project:
      - Initial ideas: project/project.md
  - Reflections:
    - Term 1:
      - First Week:
          - Landing: term1/01-Landing-Week/Landing.md
      - Atlas of Weak Signals:
          - Atlas of Weak Signals: term1/02-Atlas-of-Weak-Signals/Atlas of Weak Signals.md
      - Documenting Design:
          - Documenting Design: term1/03-Documenting-Design/Documenting Design.md
      - Design Studio:
          - Design Studio: term1/04-Design-Studio/Design Studio.md
      - The Machine Paradox: 
          - The Machine Paradox: term1/05-The-Machine-Paradox/01-The Machine Paradox.md
          - The Almost Useful Machine: term1/05-The-Machine-Paradox/02-The Almost Useful Machine.md
      - Living With Your Own Ideas: 
          - Magic Machines: term1/06-Living-With-Your-Own-Ideas/01-Magic Machines.md
          - First Person Perspective Research: term1/06-Living-With-Your-Own-Ideas/02-First Person Perspective Research.md
      - Biology Zero:
          - Biology Zero: term1/07-Biology-Zero/01-Bio Zero.md
      - Agriculture Zero:
          - Agriculture Zero: term1/08-Agriculture-Zero/01-Agri Zero.md
      - Design with Others: 
          - Design with Others: term1/09-Design-With-Others/01-Design with others.md
      - Extended Intelligences:
          - Extended Intelligences: term1/10-Extended-Intelligences/01-Extended Intelligences.md
      - Design Dialogues:
          - Design Dialogues: term1/11-Design-Dialogues/01-Design Dialogues.md
    - Term 2:
      - Design Studio 2: 
          - Design Studio2: term2/01-Design-Studio-2/01-Design Studio 2.md
      - Designing for a State of Climate Emergency: 
          - Designing for a State of Climate Emergency: term2/02-State-of-Climate-Emergency/02-Design for a State of Climate Emergency.md
      - Communicating Ideas: 
          - Communicating Ideas: term2/03-Communicating-Ideas/03-Communicating Ideas.md
      - Future Talk: 
          - Future Talk: term2/04-Future-Talk/04-Future Talk.md
      - Digital Prototyping: 
          - Digital Prototyping: term2/05-Digital-Prototyping/05-Digital Prototyping.md
      - Intro to BioMaterials: 
          - Intro to BioMaterials: term2/06-Intro-to-Biomaterials/06-Intro to Biomaterials.md
      - Fair Futures: 
          - Fair Futures: term2/07-Fair-Futures/07-Fair Futures.md




extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/thumbnail_sketches
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/jorge-de-la-mora-4b44059b/"
    - icon: fontawesome/brands/github
      link: "https://github.com/JDLM92/MDEFsite"

theme:
  name: material
  palette:
    - scheme: default
      primary: deep orange
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue gray
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    # See available fonts at https://fonts.google.com/
    text: Lato
    code: Pixelify Sans
  logo: images/JDLMicon1.svg
  favicon: images/favicon.svg
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - glightbox:
       touchNavigation: true
       loop: true
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed


extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
