# Replace the text below to customize your site
site_name: Jorge De la Mora | MDEF & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: Jorge DLM
copyright: Copyleft 2023 "Jorge De la Mora"
repo_name: 'JDLM : Github Repo'
site_url: https://jdlm92.github.io/MDEFsite/
repo_url: 'https://github.com/JDLM92/MDEFsite'


nav:
  - Home: index.md
  - About: about/me.md
  - Master project:
      - Initial ideas: project/project.md
  - Reflections:
    - Term 1:
        - First Week:
            - Landing: term1/01-Landing-Week/Landing.md
        - Atlas of Weak Signals:
            - Atlas of Weak Signals: term1/02-Atlas-of-Weak-Signals/Atlas of Weak Signals.md
        - Documenting Design:
            - Documenting Design: term1/03-Documenting-Design/Documenting Design.md
        - Design Studio:
            - Design Studio: term1/04-Design-Studio/Design Studio.md
        - The Machine Paradox: 
            - The Machine Paradox: term1/05-The-Machine-Paradox/01-The Machine Paradox.md
            - The Almost Useful Machine: term1/05-The-Machine-Paradox/2-The Almost Useful Machine.md
        - Living With Your Own Ideas: 
            - Magic Machines: term1/06-Living-With-Your-Own-Ideas/Living With Your Own Ideas.md
            - First Person Perspective Research: term1/06-Living-With-Your-Own-Ideas/Living With Your Own Ideas.md

#      - Term 2:
#         - digi: term1/01-Bootcamp.md
#        - studio: term1/01-Bootcamp.md




extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/thumbnail_sketches
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/jorge-de-la-mora-4b44059b/"
    - icon: fontawesome/brands/github
      link: "https://github.com/JDLM92/MDEFsite"

theme:
  name: material
  palette:
     # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: my-theme
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
  font:
    # See available fonts at https://fonts.google.com/
    text: Lato
    code: Pixelify Sans
  logo: images/JDLMicon1.svg
  favicon: images/favicon.svg
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - glightbox:
       touchNavigation: true
       loop: true
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.escapeall:
      hardbreak: true
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true


extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
